routes/web.php
<?php

use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\Auth\GoogleSigninController;
use App\Http\Controllers\JobPostController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RecruiterController;
use App\Http\Controllers\RecruiterProfileController;
use App\Http\Controllers\SeekerController;
use App\Http\Controllers\SeekerProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth', 'verified'])->group(function (){

    Route::middleware('recruiter')->group(function () {

        Route::get('/dashboardRe', [JobPostController::class, 'index'])->name('dashboardRe');
        Route::resource('jobs',JobPostController::class);
        Route::resource('profile', RecruiterProfileController::class);
        Route::get('/seekers', [RecruiterController::class, 'search'])->name('user.search');

    });

    Route::resource('application', ApplicationController::class);
    Route::get('selects/{id}', [ApplicationController::class, 'update'])->name('selected');

    Route::middleware('seeker')->group(function () {

        Route::get('/dashboard', [SeekerController::class, 'index'])->name('dashboard');
        Route::get('/display/{uuid}', [JobPostController::class, 'show'])->name('display');
        Route::resource('profiles', SeekerProfileController::class);
        Route::get('apply/{id}', [ApplicationController::class, 'create'])->name('apply');

    });
});


Route::post('googleIn',[GoogleSigninController::class, 'update'])->name('googleIn');
Route::get('roles',[GoogleSigninController::class, 'create'])->name('create');
Route::get('googles',[GoogleSigninController::class, 'signUpGoogle'])->name('signUp');
Route::get('SignIn',[GoogleSigninController::class, 'signInGoogle'])->name('signIn');
Route::get('google',[GoogleSigninController::class, 'getData'])->name('google');

require __DIR__.'/auth.php';

app/Http/Controllers/RecruiterController.php
<?php

namespace App\Http\Controllers;

use App\Http\Services\LocationSeparator;
use App\Models\SeekerProfile;
use App\Models\skill;
use Illuminate\Http\Request;

class RecruiterController extends Controller
{
    public function search(Request $request)
    {

        $skills = skill::get();
        $seekers = SeekerProfile::select('college', 'location')->distinct()->get();

        $location = new LocationSeparator();
        $uniqueLocations = $location->trim($seekers);

        $query = $this->filter($request);
        $users = $query->paginate(5);

        return view('recruiter.userSearch',
        ['users'=>$users,
            'seekers'=>$seekers,
            'skills'=>$skills,
            'location'=>$uniqueLocations,
            ]
        );
    }

    public function filter($request){

        return SeekerProfile::query()->where('status',0)->with('skill')

        ->when($request->location, function ($query, $location) {
            $get = new LocationSeparator();
            $get->finder($query, $location);
        })

        ->when($request->college, function ($query, $college) {
                $query->where('college', $college);
        })

        ->when($request->skill, function ($query, $skill){
            $query->whereHas('skill', function ($query) use ($skill) {
                $query->where('id', $skill);
            });
        });

    }
}

resources/views/recruiter/applicant.blade.php
@extends('components.base')

@section('content')
    <div class="sec">
        <div class="backdesign">
            <h4>The Applicant who have applied for this job.. </h4>
        </div>
        @foreach( $applications as $applicant)
        <div class="secbody">
            <div class="job">
                <div class="item">
                    <div class="pho">
                        <div class="phot">
                            <img class="phot" src="{{asset('/images/seeker/'.$applicant->SeekerProfile->image)}}">
                        </div>
                        <div class="cont">
                            <h2>{{ $applicant->seekerProfile->firstname." ". $applicant->seekerProfile->lastname}}</h2>
                            <h4>{{$applicant->jobPost->jobType->name}}</h4>
                            <div class="change">
                                <p>Has applied For: {{ $applicant->jobPost->title }}</p>
                            </div>
                            <em>Job Posted on: {{ $applicant->jobPost->created_at }}</em><br>
                            <em>Applied date: {{ $applicant->created_at }}</em>
                        </div>
                    </div>
                    <div class="btn">
                        <a href="/cv/{{ $applicant->seekerProfile->cv }}" download>download cv</a>
                        @if($applicant->status == 'applied')
                            <a class="sel" href="{{ route('selected', $applicant->id) }}" onclick=" return action()">Select</a>
                        @else
                            <form action="{{ route('selected', $applicant->id) }}" method="get">
                                @method('put')
                                <input type="text" name="link"><button type="submit">Add Exam Link</button>
                            </form>
                        @endif
                        <a class="del" href="{{ route('application.edit', $applicant->id) }}" onclick=" return action()" >Reject</a>
                    </div>
                </div>
            </div>
        </div>
        @endforeach
    </div>
@endsection
<script>
    function action(){
        return confirm('Are you sure you want to perform this action?');
    }
</script>

resources/views/recruiter/userSearch.blade.php
@extends('components.base')

@section('content')
    <div class="sec">
        <div class="backdesign">
            <h4>You can find the jobs according to your interest.</h4>
        </div>
        <div class="secbody">
            <div class="filter">
                <form action="{{ route('user.search') }}" method="get">
                    <select name="location">
                        <option value=" ">Choose Location</option>
                        @foreach($location as $seeker)
                        <option value="{{ $seeker }}">{{ $seeker }}</option>
                        @endforeach
                    </select><br>
                    <select name="college">
                        <option value=" ">Choose college</option>
                    @foreach($seekers as $seeker)
                            <option value="{{ $seeker->college }}">{{ $seeker->college }}</option>
                        @endforeach                    </select><br>
                    <select name="skill">
                        <option value=" ">Choose skill</option>
                    @foreach($skills as $skill)
                            <option value="{{ $skill->id }}">{{ $skill->name }}</option>
                        @endforeach                    </select><br>
                    <input type="submit" name="submit" value="Filter">
                </form>
            </div>
            <div class="job">
                @foreach($users as $user)
                <div class="item">
                    <div class="pho">
                        <div class="phot">
                            <img class="phot" src="{{asset('/images/seeker/'.$user->image)}}" alt="Company Image">
                        </div>
                        <div class="cont">
                            <h2>{{ $user->firstname ." ". $user->lastname }}</h2>
                            <h5>{{ $user->location }}</h5>
                            <h5>{{ $user->college }}</h5>
                            <div class="change">
                                @foreach( $user->skill as $skill)
                                    <h5>{{$skill->name}}</h5>
                                @endforeach
                            </div>
                            <a href="/cv/{{ $user->cv }}" download>download cv</a>
                        </div>
                    </div>
                </div>
                @endforeach
                <div class="pagi">
                    {{ $users->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection