routes/web.php
<?php

use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\Auth\GoogleSigninController;
use App\Http\Controllers\JobPostController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RecruiterController;
use App\Http\Controllers\RecruiterProfileController;
use App\Http\Controllers\SeekerController;
use App\Http\Controllers\SeekerProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth', 'verified'])->group(function (){

    Route::middleware('recruiter')->group(function () {

        Route::get('/dashboardRe', [JobPostController::class, 'index'])->name('dashboardRe');
        Route::resource('jobs',JobPostController::class);
        Route::resource('profile', RecruiterProfileController::class);
        Route::get('/seekers', [RecruiterController::class, 'search'])->name('user.search');

    });

    Route::resource('application', ApplicationController::class);
    Route::get('selects/{id}', [ApplicationController::class, 'update'])->name('selected');

    Route::middleware('seeker')->group(function () {

        Route::get('/dashboard', [SeekerController::class, 'index'])->name('dashboard');
        Route::get('/display/{uuid}', [JobPostController::class, 'show'])->name('display');
        Route::resource('profiles', SeekerProfileController::class);
        Route::get('apply/{id}', [ApplicationController::class, 'create'])->name('apply');

    });
});


Route::post('googleIn',[GoogleSigninController::class, 'update'])->name('googleIn');
Route::get('roles',[GoogleSigninController::class, 'create'])->name('create');
Route::get('googles',[GoogleSigninController::class, 'signUpGoogle'])->name('signUp');
Route::get('SignIn',[GoogleSigninController::class, 'signInGoogle'])->name('signIn');
Route::get('google',[GoogleSigninController::class, 'getData'])->name('google');

require __DIR__.'/auth.php';

app/Http/Controllers/SeekerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Services\LocationSeparator;
use App\Models\JobPost;
use App\Models\JobType;
use App\Models\RecruiterProfile;
use App\Models\SeekerProfile;
use App\Models\skill;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SeekerController extends Controller
{

    public function index(Request $request)
    {

        $logUser = SeekerProfile::where('user_id', Auth::user()->id)->first();

        $skill = Skill::get();
        $type = JobType::get();
        $company = RecruiterProfile::get();
        $seekers= JobPost::select('location')->distinct()->get();

        $location = new LocationSeparator();
        $uniqueLocations = $location->trim($seekers);

        if (!$logUser) {
            return redirect()->route('profiles.create');
        }
        $query = $this->filter($request);

        $postData = $query->where('deadline','>=', now())->latest('created_at')->paginate(5);
            return view('seeker.dashboard', [
                'posts' => $postData,
                'skill'=>$skill,
                'type'=>$type,
                'location'=>$uniqueLocations,
                'company'=>$company,
            ]);
    }

    public function filter($request){

        $query = JobPost::with('recruiterProfile', 'postSkill', 'jobType')
                ->when($request->location, function ($query, $location) {
                    $get = new LocationSeparator();
                    $get->finder($query, $location);
                })
                ->when($request->company, function ($query, $company) {
                    $query->whereHas('recruiterProfile', function ($query) use ($company) {
                        $query->where('company_name', $company);
                    });
                })
                ->when($request->type, function ($query, $type) {
                    $query->where('type_id', $type);
                })
                ->when($request->skill, function ($query, $skill) {
                    $query->whereHas('postSkill', function ($query) use ($skill) {
                        $query->where('id', $skill);
                    });
                });

            return $query;

        }






}

resources/views/seeker/profile/create.blade.php
@extends('components.base')

@section('content')
    <div class="contai">
        <div class="job_container">
            <h1>COMPLETE YOUR PROFILE</h1><br>
            <form action="{{ route('profiles.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <label for="firstname">Firstname: </label>
                <input type="text" name="firstname" placeholder="john">
                @error('firstname') {{ $message }} @enderror
                <br><br>
                <label for="lastname">Lastname: </label>
                <input type="text" name="lastname" placeholder="doe">
                @error('lastname') {{ $message }} @enderror
                <br><br>
                <label for="location">Location: </label>
                <input type="text" name="location" placeholder="Lagankhel, kathmandu OR Lagenkhel-01, kathmandu">
                @error('location') {{ $message }} @enderror
                <br><br>
                <label for="contact_number">Contact Number: </label>
                <input type="text" name="contact_number" placeholder="9812675211">
                @error('contact_number') {{ $message }} @enderror
                <br><br>
                <label for="skill">Skills that you have: </label>
                <div class="double">
                    @foreach($skills as $skill)
                        <input type="checkbox" name="skill[]" value="{{ $skill->id }}">
                        <label>{{ $skill->name }}</label>
                    @endforeach
                </div>
                <br>
                <label for="qualification">Highest Qualification: </label>
                <input type="text" name="qualification" placeholder="Qualification" >
                @error('qualification') {{ $message }} @enderror
                <br><br>
                <label for="college">College Name: </label>
                <input type="text" name="college" placeholder="college">
                @error('college') {{ $message }} @enderror
                <br><br>
                <label for="image">Current Image: </label>
                <input type="file" accept="image/*" name="image" >
                @error('image') {{ $message }} @enderror
                <br><br>
                <label for="cv">CV: </label>
                <input type="file" accept=".doc, .docx, .pdf" name="cv" >
                @error('cv') {{ $message }} @enderror
                <br><br>
                <label for="about">About Yourself: </label>
                <textarea name="about" placeholder="Add about you here"></textarea>
                @error('about') {{ $message }} @enderror
                <br><br>
                <label for="experience">Experience: </label>
                <textarea name="experience" placeholder="Add the job Experience here..."></textarea>
                @error('experience') {{ $message }} @enderror
                <br><br>
                <label for="description">Why do you want to Join us: </label>
                <textarea name="description" placeholder="Add reason here..."></textarea>
                @error('description') {{ $message }} @enderror
                <br><br>
                <button type="submit" name="submit">Profile Complete</button>
            </form>
        </div>
    </div>
@endsection

resources/views/seeker/profile/show.blade.php
@extends('components.base')

@section('content')
    <div class="bodys">
        @if(Session::has('message'))
            <p>{{ Session::get('message') }}</p>
        @endif
        <div class="img">
            <div class="imgs">
                <img  class="imgs" src="{{asset('/images/seeker/'.$profile->image)}}">
            </div>
            <div class="profil">
                <h2>{{ $profile->firstname. " ". $profile->lastname }}</h2>
                <em>joined date: {{ $profile->created_at }}</em>
                <h4>{{ $profile->user->email }}</h4>
                <h4>{{ $profile->contact_number }}</h4>
                <h4>{{ $profile->location }}</h4>
            </div>
        </div>
        @if($profile->status == 0)
            <a class="status" href="#">Active</a>
        @else
            <a class="status" href="#">Inactive</a>
        @endif

        <div class="detail">
            <div class="skill">
                <h2>Skills:</h2>
                @foreach($profile->skill as $skills)
                    <p>{{ $skills->name }}</p>
                @endforeach
            </div>
        </div>
        <div class="detail">
            <h3> College Name: {{ $profile->college }}</h3>
            <br><h3>Education:</h3>
            <p>{{$profile->qualification}}</p>
        </div>
        <div class="detail">
            <h2>About Yourself:</h2>
            <p>{{ $profile->about }}</p>
        </div>
        <div class="detail">
            <h2>Experience:</h2>
            <p>{{ $profile->experience }}</p>
        </div>
        <div class="detail">
            <h2>Why Are You Searching For JOb:</h2>
            <p>{{ $profile->description }}</p>
        </div>
        <a href="/cv/{{ $profile->cv }}" download>download cv</a>
        <a class="update" href="{{ route('profiles.edit', $profile->id) }}">Update Profile</a>
    </div>
@endsection

resources/views/seeker/profile/update.blade.php
@extends('components.base')

@section('content')
    <div class="contai">
        <div class="job_container">
            <h1>UPDATE YOUTR PROFILE</h1><br>
            <form action="{{ route('profiles.update',$profile->id) }}" method="post" enctype="multipart/form-data">
                @method('put')
                @csrf
                <label for="email">E-mail: </label>
                <input type="email" name="email" placeholder="email" value="{{ $profile->user->email }}">
                <br><br>
                <label for="firstname">Firstname: </label>
                <input type="text" name="firstname" placeholder="john" value="{{ $profile->firstname }}">
                @error('firstname') {{ $message }} @enderror
                <br><br>
                <label for="lastname">Lastname: </label>
                <input type="text" name="lastname" placeholder="doe" value="{{ $profile->lastname }}">
                @error('lastname') {{ $message }} @enderror
                <br><br>
                <label for="location">Location: </label>
                <input type="text" name="location" placeholder="Lagankhel, kathmandu OR Lagenkhel-01, kathmandu" value="{{ $profile->location }}">
                @error('location') {{ $message }} @enderror
                <br><br>
                <label for="contact_number">Contact Number: </label>
                <input type="text" name="contact_number" placeholder="9812675211" value="{{ $profile->contact_number }}">
                @error('contact_number') {{ $message }} @enderror
                <br><br>
                <label for="status">Status: </label>
                <select name="status">
                    <option value="0">active</option>
                    <option value="1">Not Active</option>
                </select>
                <br>
                <label for="skill[]">Skills Required: </label>
                <div class="double">
                    @foreach($skills as $skill)
                        <input type="checkbox" name="skill[]" value="{{ $skill->id }}"
                               @if(in_array($skill->id,$selectedSkills)) checked @endif>
                        <label>{{ $skill->name }}</label>
                    @endforeach
                </div>
                <br>
                <label for="qualification">Highest Qualification: </label>
                <input type="text" name="qualification" placeholder="Qualification" value="{{ $profile->qualification }}">
                @error('qualification') {{ $message }} @enderror
                <br><br>
                <label for="college">College Name: </label>
                <input type="text" name="college" placeholder="college" value="{{ $profile->college }}">
                @error('college') {{ $message }} @enderror
                <br><br>
                <label for="image">Current Image:</label>
                <input type="file" accept="image/*" name="image">
                @error('image') {{ $message }} @enderror
                <br><br>
                <label for="cv">CV: </label>
                <input type="file" accept=".doc, .docx, .pdf" name="cv" >
                @error('cv') {{ $message }} @enderror<br><br>
                <label for="about">About Yourself: </label>
                <textarea name="about" placeholder="Add about you here">
                    {{ $profile->about }}
                </textarea>
                @error('about') {{ $message }} @enderror
                <br><br>
                <label for="experience">Experience: </label>
                <textarea name="experience" placeholder="Add the job Experience here...">
                    {{ $profile->experience }}
                </textarea>
                @error('experience') {{ $message }} @enderror
                <br><br>
                <label for="description">Why do you want to Join us: </label>
                <textarea name="description" placeholder="Add the job Experience here...">
                    {{ $profile->description }}
                </textarea>
                @error('description') {{ $message }} @enderror<br><br>
                <button type="submit" name="submit">Update Profile</button>
            </form>
        </div>
    </div>
@endsection