routes/web.php
<?php

use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\Auth\GoogleSigninController;
use App\Http\Controllers\JobPostController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RecruiterController;
use App\Http\Controllers\RecruiterProfileController;
use App\Http\Controllers\SeekerController;
use App\Http\Controllers\SeekerProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth', 'verified'])->group(function (){

    Route::middleware('recruiter')->group(function () {

        Route::get('/dashboardRe', [JobPostController::class, 'index'])->name('dashboardRe');
        Route::resource('jobs',JobPostController::class);
        Route::resource('profile', RecruiterProfileController::class);
        Route::get('/seekers', [RecruiterController::class, 'search'])->name('user.search');

    });

    Route::resource('application', ApplicationController::class);
    Route::get('selects/{id}', [ApplicationController::class, 'update'])->name('selected');

    Route::middleware('seeker')->group(function () {

        Route::get('/dashboard', [SeekerController::class, 'index'])->name('dashboard');
        Route::get('/display/{uuid}', [JobPostController::class, 'show'])->name('display');
        Route::resource('profiles', SeekerProfileController::class);
        Route::get('apply/{id}', [ApplicationController::class, 'create'])->name('apply');

    });
});


Route::post('googleIn',[GoogleSigninController::class, 'update'])->name('googleIn');
Route::get('roles',[GoogleSigninController::class, 'create'])->name('create');
Route::get('googles',[GoogleSigninController::class, 'signUpGoogle'])->name('signUp');
Route::get('SignIn',[GoogleSigninController::class, 'signInGoogle'])->name('signIn');
Route::get('google',[GoogleSigninController::class, 'getData'])->name('google');

require __DIR__.'/auth.php';

app/Http/Controllers/RecruiterController.php
<?php

namespace App\Http\Controllers;

use App\Http\Services\LocationSeparator;
use App\Models\SeekerProfile;
use App\Models\skill;
use Illuminate\Http\Request;

class RecruiterController extends Controller
{
    public function search(Request $request)
    {

        $skills = skill::get();
        $seekers = SeekerProfile::select('college', 'location')->distinct()->get();

        $location = new LocationSeparator();
        $uniqueLocations = $location->trim($seekers);

        $query = $this->filter($request);
        $users = $query->paginate(5);

        return view('recruiter.userSearch',
        ['users'=>$users,
            'seekers'=>$seekers,
            'skills'=>$skills,
            'location'=>$uniqueLocations,
            ]
        );
    }

    public function filter($request){

        return SeekerProfile::query()->where('status',0)->with('skill')

        ->when($request->location, function ($query, $location) {
            $get = new LocationSeparator();
            $get->finder($query, $location);
        })

        ->when($request->college, function ($query, $college) {
                $query->where('college', $college);
        })

        ->when($request->skill, function ($query, $skill){
            $query->whereHas('skill', function ($query) use ($skill) {
                $query->where('id', $skill);
            });
        });

    }
}

resources/views/recruiter/profile/create.blade.php
@extends('components.base')

@section('content')
    <div class="contai">
        <div class="job_container">
            <h1>COMPLETE THE RECRUITER PROFILE</h1><br>
            <form action="{{ route('profile.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <label for="company_name">Company Name: </label>
                <input type="text" name="company_name" placeholder="Buddha">
                @error('company_name')
                   {{ $message }}
                @enderror
                <br><br>
                <label for="location">Location: </label>
                <input type="text" name="location" placeholder="Lagankhel, kathmandu OR Lagenkhel-01, kathmandu">
                @error('location')
                   {{ $message }}
                @enderror
                <br><br>
                <label for="contact_number">Contact_number: </label>
                <input type="text" name="contact_number" placeholder="Qualification" >
                @error('contact_number')
                    {{ $message }}
                @enderror
                <br><br>
                <label for="image">Company Image</label>
                <input type="file" accept="image/*" name="image">
                @error('image')
                    {{ $message }}
                @enderror
                <br><br>
                <label for="detail">Company Detail: </label>
                <textarea name="detail" placeholder="Add the job perks and Benefits here"></textarea>
                @error('detail')
                    {{ $message }}
                @enderror
                <br><br>
                <button type="submit" name="submit">Complete Profile</button>
            </form>
        </div>
    </div>
@endsection

resources/views/recruiter/profile/show.blade.php
@extends('components.base')

@section('content')
    <div class="bodys">
        @if(Session::has('message'))
            <p>{{ Session::get('message') }}</p>
        @endif
        <div class="img">
            <div class="imgs">
                <img class="imgs" src="{{asset('/images/recruiter/'.$profile->image)}}" alt="Company Image">
            </div>
            <div class="profil">
                <h2>{{ $profile->company_name }}</h2>
                <em>joined date: {{ $profile->created_at }}</em>
                <h4>{{$profile->user->email}}</h4>
                <h4>{{ $profile->contact_number }}</h4>
                <h4>{{$profile->location}}</h4>
            </div>
        </div>
        <div class="detail">
            <h2>Company description:</h2>
            <p>{{ $profile->detail }}</p>
        </div>
    </div>
        <a class="update" href="{{ route('profile.edit', 'updatingUser') }}">Update Profile</a>
@endsection

resources/views/recruiter/profile/update.blade.php
@extends('components.base')

@section('content')
    <div class="contai">
        <div class="job_container">
            <h1>UPDATE RECRUITER PROFILE</h1><br>
            <form action="{{ route('profile.update',$profile->id) }}" method="post" enctype="multipart/form-data">
                @method('put')
                @csrf
                <label for="email">E-mail: </label>
                <input type="email" name="email" placeholder="email" value="{{ $profile->user->email }}">
                <br><br>
                <label for="company_name">Company Name: </label>
                <input type="text" name="company_name" placeholder="Buddha" value="{{ $profile->company_name }}">
                <br><br>
                <label for="location">Location: </label>
                <input type="text" name="location" placeholder="Lagankhel, kathmandu OR Lagenkhel-01, kathmandu" value="{{$profile->location}}">
                @error('location')
                  {{ $message }}
                @enderror
                <br><br>
                <label for="contact_number">Contact_number: </label>
                <input type="text" name="contact_number" placeholder="number" value="{{ $profile->contact_number }}">
                @error('contact_number')
                   {{ $message }}
                @enderror
                <br><br>
                <label for="image">Company Image</label>
                <input type="file" accept="image/*" name="image" value="{{ $profile->image }}">
                @error('image')
                   {{ $message }}
                @enderror
                <br><br>
                <label for="detail">Company Detail: </label>
                <textarea name="detail" placeholder="Add the job perks and Benefits here">
                    {{ $profile->detail }}
                </textarea>
                <br><br>
                <button type="submit" name="submit">Update Profile</button>
            </form>
        </div>
    </div>
@endsection