routes/web.php
<?php

use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\Auth\GoogleSigninController;
use App\Http\Controllers\JobPostController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RecruiterController;
use App\Http\Controllers\RecruiterProfileController;
use App\Http\Controllers\SeekerController;
use App\Http\Controllers\SeekerProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth', 'verified'])->group(function (){

    Route::middleware('recruiter')->group(function () {

        Route::get('/dashboardRe', [JobPostController::class, 'index'])->name('dashboardRe');
        Route::resource('jobs',JobPostController::class);
        Route::resource('profile', RecruiterProfileController::class);
        Route::get('/seekers', [RecruiterController::class, 'search'])->name('user.search');

    });

    Route::resource('application', ApplicationController::class);
    Route::get('selects/{id}', [ApplicationController::class, 'update'])->name('selected');

    Route::middleware('seeker')->group(function () {

        Route::get('/dashboard', [SeekerController::class, 'index'])->name('dashboard');
        Route::get('/display/{uuid}', [JobPostController::class, 'show'])->name('display');
        Route::resource('profiles', SeekerProfileController::class);
        Route::get('apply/{id}', [ApplicationController::class, 'create'])->name('apply');

    });
});


Route::post('googleIn',[GoogleSigninController::class, 'update'])->name('googleIn');
Route::get('roles',[GoogleSigninController::class, 'create'])->name('create');
Route::get('googles',[GoogleSigninController::class, 'signUpGoogle'])->name('signUp');
Route::get('SignIn',[GoogleSigninController::class, 'signInGoogle'])->name('signIn');
Route::get('google',[GoogleSigninController::class, 'getData'])->name('google');

require __DIR__.'/auth.php';

app/Http/Controllers/RecruiterController.php
<?php

namespace App\Http\Controllers;

use App\Http\Services\LocationSeparator;
use App\Models\SeekerProfile;
use App\Models\skill;
use Illuminate\Http\Request;

class RecruiterController extends Controller
{
    public function search(Request $request)
    {

        $skills = skill::get();
        $seekers = SeekerProfile::select('college', 'location')->distinct()->get();

        $location = new LocationSeparator();
        $uniqueLocations = $location->trim($seekers);

        $query = $this->filter($request);
        $users = $query->paginate(5);

        return view('recruiter.userSearch',
        ['users'=>$users,
            'seekers'=>$seekers,
            'skills'=>$skills,
            'location'=>$uniqueLocations,
            ]
        );
    }

    public function filter($request){

        return SeekerProfile::query()->where('status',0)->with('skill')

        ->when($request->location, function ($query, $location) {
            $get = new LocationSeparator();
            $get->finder($query, $location);
        })

        ->when($request->college, function ($query, $college) {
                $query->where('college', $college);
        })

        ->when($request->skill, function ($query, $skill){
            $query->whereHas('skill', function ($query) use ($skill) {
                $query->where('id', $skill);
            });
        });

    }
}

resources/views/recruiter/post/create.blade.php
@extends('components.base')

@section('content')
    <div class="contai">
        <div class="job_container">
            <h1>ADD NEW JOB POST</h1><br>
            <form action="{{ route('jobs.store') }}" method="post">
                @method('post')
                @csrf
                <label for="title">Title: </label>
                <input type="text" name="title" placeholder="job Title" value="{{ old('title') }}">
                <p>
                    @error('title'){{ $message }}@enderror
                </p>
                <br><br>
                <label for="location">Location: </label>
                <input type="text" name="location" placeholder="Lagankhel, kathmandu OR Lagenkhel-01, kathmandu" value="{{ old('location') }}">
                <p>
                    @error('location'){{ $message }} @enderror
                </p>
                <br><br>
                <label for="deadline">Deadline: </label>
                <input type="datetime-local" name="deadline"   value="{{ old('deadline') }}">
                <p>
                    @error('deadline'){{ $message }}@enderror
                </p>
                <br><br>
                <label for="skill">Skills Required: </label>
                <div class="double">
                    @foreach($skills as $skill)
                        <input type="checkbox" name="skill[]" value="{{ $skill->id }}"><label>{{ $skill->name }}</label>
                    @endforeach
                </div>
                <p>
                    @error('skill'){{ $message }}@enderror
                </p>
                <br>
                <label for="type_id">Job Types: </label>
                <select class="type" name="type_id" >
                    <option value="">Choose Job-Type</option>
                    @foreach($types as $type)
                        <option value="{{ $type->id }}">{{ $type->name }}</option>
                    @endforeach
                </select>
                <p>
                    @error('type_id'){{ $message }}@enderror
                </p>
                <br><br>
                <label for="qualification">Qualification: </label>
                <input type="text" name="qualification" placeholder="Qualification" value="{{ old('qualification') }}">
                <p>
                    @error('qualification'){{ $message }}@enderror
                </p>
                <br><br>
                <label for="experience">Experience: </label>
                <input type="text" name="experience" placeholder="Experience" value="{{ old('experience') }}">
                <p>
                    @error('experience'){{ $message }}@enderror
                </p>
                <br><br>
                <label for="vacancy">Vacancy: </label>
                <input type="number" name="vacancy" placeholder="Vancancy" value="{{ old('vacancy') }}">
                <p>
                    @error('vacancy'){{ $message }}@enderror
                </p>
                <br><br>
                <label for="description">Description: </label>
                <textarea name="description" placeholder="Add the job description here" >
                    {{ old('description') }}
                </textarea>
                <p>
                    @error('description'){{ $message }}@enderror
                </p>
                <br><br>
                <label for="responsibility">Responsibility: </label>
                <textarea name="responsibility" placeholder="Add the job Responsibility here...">
                    {{old('responsibility')}}
                </textarea>
                <p>
                    @error('responsibility'){{ $message }}@enderror
                </p>
                <br><br>
                <label for="benefit">Benefit: </label>
                <textarea name="benefit" placeholder="Add the job perks and Benefits here">
                    {{ old('benefit') }}
                </textarea>
                <p>
                    @error('benefit'){{ $message }}@enderror
                </p>
                <br><br>
                <button type="submit" name="submit">
                    ADD JOB
                </button>
            </form>
        </div>
    </div>
@endsection

resources/views/recruiter/post/dashboard.blade.php
@extends('components.base')

@section('content')
    <div class="sec">
        <div class="backdesign">
            <h4>The job that you have posted.</h4>
        </div>
        @if(Session::has('message'))
            <p>{{ Session::get('message') }}</p>
        @endif
        @foreach( $posts as $post)
            <div class="secbody">
                <div class="job">
                    <div class="item">
                        <div class="pho">
                            <div class="photo">
                                <img class="photo" src="{{asset('/images/recruiter/'.$post->recruiterProfile->image)}}" alt="Company image">
                            </div>
                            <div class="cont">
                                <h2>{{ $post->title }}</h2>
                                <h4>{{ $post->jobType->name }}</h4>
                                <div class="change">
                                    <h6>{{$post->location}}</h6>
                                    @foreach($post->postSkill as $skill )
                                        <h5>{{ $skill->name }}</h5>
                                    @endforeach
                                </div>
                                @if($post->deadline >= now())
                                    <h4 >FEATURED</h4>
                                @else
                                    <h4 class="de">EXPIRED</h4>
                                @endif
                                <h5>{{ $post->recruiterProfile->company_name }}</h5>
                                <h5>Apply before:{{ $post->deadline }}</h5>
                            </div>
                        </div>
                        <a href="{{ route('jobs.show',$post->uuid) }}">View</a>
                    </div>
                </div>
            </div>
        @endforeach
        <div class="pagi">
            {{ $posts->links() }}
        </div>
    </div>
@endsection

resources/views/recruiter/post/show.blade.php
@extends('components.base')

@section('content')
    <div class="bodys">
        @if(Session::has('message'))
            <p>{{ Session::get('message') }}</p>
        @endif
        <div class="img">
            <div class="imgs">
                <img class="imgs" src="{{asset('/images/recruiter/'.$posts->recruiterProfile->image)}}">
            </div>
            <div class="profil">
                <h2>{{ $posts->title }}</h2>
                <em>posted on: {{ $posts->created_at }}</em>
                <h4>{{ $posts->recruiterProfile->email }}</h4>
                <h4>{{$posts->recruiterProfile->company_name}}</h4>
                <h4>{{$posts->location}}</h4>
                <em>Apply Before: {{ $posts->deadline }}</em>
                <h4>{{$posts->jobType->name}}</h4>
            </div>
        </div>
        <div class="detail">
            <div class="skill">
                <h2>Skills:</h2>
                @foreach($posts->postSkill as $skills)
                    <p>{{ $skills->name }}</p>
                @endforeach
            </div>
        </div>
        <div class="detail">
            <h2>Job Description:</h2>
            <p>{{ $posts->description }}</p>
        </div>
        <div class="detail">
            <p>Qalification Required: {{$posts->qualification}}</p>
            <p>Experience Required: {{$posts->experience}}</p>
            <p>No. of Vacancy: [{{ $posts->vacancy }}]</p>
        </div>
        <div class="detail">
            <h2>Responsibility:</h2>
            <pre><p>{{$posts->responsibility}}</p></pre>
        </div>
        <div class="detail">
            <h2>Benefits and Perks:</h2>
            <pre><p>{{$posts->benefit}}</p></pre>
        </div>
        @if(Auth::user()->role =='recruiter')
            <a class="update" href="{{ route('jobs.edit',$posts->uuid) }}">Update Post</a>
            <a href="{{ route('application.show', $posts->uuid) }}">Applicant</a>
        @elseif(Auth::user()->role=='seeker')
            @forelse($posts->application as $applied)
                @if($applied->post_id == $posts->id && $applied->seekerProfile->user_id == Auth::user()->id)
                    You have already applied for this job
                @endif
            @empty
                <a class="update" id="apply" href="{{ route('apply',$posts->uuid) }}" onclick="return ruleApply()" data-id="{{ $posts->uuid }}">APPLY</a>
            @endforelse
        @endif
    </div>
@endsection
<script>
    function ruleApply(){
        return confirm('Do you sure to apply for this job {{ $posts->title }}?');
    }

    {{--function clickFunc() {--}}
    {{--    let applyBtn = document.getElementById('apply');--}}
    {{--    let postId = applyBtn.getAttribute('data-id');--}}
    {{--    let text = "Press a button!\nEither OK or Cancel.";--}}
    {{--    if (confirm(text) == true) {--}}
    {{--        let link = '{{ route('apply', ':id') }}';--}}
    {{--        link = link.replace(':id', postId);--}}
    {{--        apply.setAttribute("href", link);--}}
    {{--    }--}}
    {{--}--}}

</script>

resources/views/recruiter/post/update.blade.php
@extends('components.base')

@section('content')
    <div class="contai">
        <div class="job_container">
            <h1>UPDATE JOB POST</h1><br>
            <form action="{{ route('jobs.update', $post->id) }}" method="post">
                @method('put')
                @csrf
                <label for="title">Title: </label>
                <input type="text" name="title" placeholder="job Title" value="{{ $post->title }}">
                <p>
                    @error('title'){{ $message }}@enderror
                </p>
                <br><br>
                <label for="location">Location: </label>
                <input type="text" name="location" placeholder="Lagankhel, kathmandu OR Lagenkhel-01, kathmandu" value="{{ $post->location }}">
                <p>
                    @error('location'){{ $message }}@enderror
                </p>
                <br><br>
                <label for="deadline">Deadline: </label>
                <input type="datetime-local" name="deadline" value="{{ $post->deadline }}">
                <p>
                    @error('deadline') {{ $message }}@enderror
                </p>
                <br><br>
                <label for="skill[]">Skills Required: </label>
                <div class="double">
                    @foreach($skills as $skill)
                        <input type="checkbox" name="skill[]" value="{{ $skill->id }}"
                               @if(in_array($skill->id,$selectedSkills))
                                   checked
                            @endif>
                        <label>
                            {{ $skill->name }}
                        </label>
                    @endforeach
                </div>
                <br>
                <label for="type_id">Job Types: </label>
                <select class="type" name="type_id">
                    <option value="{{ $post->type_id }}">{{ $post->jobType->name }}</option>
                    @foreach($types as $type)
                        <option value="{{ $type->id }}">{{ $type->name }}</option>
                    @endforeach
                </select>
                <br><br>
                <label for="qualification">Qualification: </label>
                <input type="text" name="qualification" placeholder="Qualification" value="{{ $post->qualification }}">
                <p>
                    @error('qualification'){{ $message }}@enderror
                </p>
                <br><br>
                <label for="experience">Experience: </label>
                <input type="text" name="experience" placeholder="Experience" value="{{ $post->experience }}">
                <p>
                    @error('experience'){{ $message }}@enderror
                </p>
                <br><br>
                <label for="vacancy">Vacancy: </label>
                <input type="number" name="vacancy" placeholder="Vancancy" value="{{ $post->vacancy }}">
                <p>
                    @error('vacancy'){{ $message }}@enderror
                </p>
                <br><br>
                <label for="description">Description: </label>
                <textarea name="description" placeholder="Add the job description here">
                    {{ $post->description }}
                </textarea>
                <p>
                    @error('description'){{ $message }}@enderror
                </p>
                <br><br>
                <label for="responsibility">Responsibility: </label>
                <textarea name="responsibility" placeholder="Add the job Responsibility here...">
                    {{ $post->responsibility }}
                </textarea>
                <p>
                    @error('responsibility'){{ $message }}@enderror
                </p>
                <br><br>
                <label for="benefit">Benefit: </label>
                <textarea name="benefit" placeholder="Add the job perks and Benefits here">
                    {{ $post->benefit }}
                </textarea>
                <p>
                    @error('benefit'){{ $message }}@enderror
                </p>
                <br><br>
                <button type="submit" name="submit">UPDATE JOB</button>
            </form>
        </div>
    </div>
@endsection